### ISSUE TITLE
Dict.cc creation missing letters&spaces

### ISSUE THREAD

**Issue by Uwe-B** [Markismus/PocketBookDic#3]
I thought you fixed it but with the last version this came up again:
1) Download vocabulary database, in your case en-de on this site (you need an mail adress for this) https://www.dict.cc/?s=about:wordlist
2) Unpack and rename properly, ending csv.
3) Remove the header entries so that the first entry is a vocabulary entry.
4) Goto https://www.mobileread.com/forums/sh...d.php?t=325203 and install pocketbook.pl properly, including perl and the tools mentioned there.
5) Use it as described on the dict.cc vocabulary list.

Results (see screenshot):
![scr0003](https://user-images.githubusercontent.com/25583567/112311578-251c3f00-8ca6-11eb-8d03-48011488565a.png)
![scr0002](https://user-images.githubusercontent.com/25583567/112311584-25b4d580-8ca6-11eb-8672-d70e762cf0c4.png)

**Comment by Uwe-B** [comment]
Found the problem, in the source (csv file) I found more than one tab per line, first is the delimiter, the others tabs are used to separate grammatical expressions. The converter later doesn't like tabs (\t):
![pocketbookdic_error](https://user-images.githubusercontent.com/25583567/112359498-9d4c2a00-8cd1-11eb-992f-eeb53f2ff215.png)
 They should probably converted into something like this (noun).

Edit: For my own purposes I just run the output through sed before sending it to the converter:
sed.exe -E -e "s/\t([^\t]+)\t/(\1)/g" -e "s/\t\t/ /g" DictCC_En-DE_reconstructed.xdxf  > DictCC_En-DE_reconstructed.2.xdxf

**Comment by Markismus** [comment]
Probably I used an overzealous approach  assuming there is only 1 delimiter character per entry.

Does the script generate badly formatted xdxf-files (as suggested by your screenshot) due to tab-characters or is `convert.exe` not able to handle tab-characters in an article?

`sed.exe -E -e "s/\t([^\t]+)\t/(\1)/g" -e "s/\t\t/ /g"` seems an odd solution. As it removes double numbered tabs, you have no control over what odd tab remains. 
Could you  use `sed.exe -E -e "s/\t/|/" DictCC_En-DE.csv` to replace the first TAB on each line with the symbol `|` and run the script with the modified csv-file. 

If the result is good, it is at least clear that the problem isn't with `convert.exe`.

**Comment by Markismus** [comment]
Looking at the code, I have no idea what the problem is. It just takes a string from the left and right of the first delimiter found on a line. See [line 557](https://github.com/Markismus/PocketBookDic/blob/master/pocketbookdic.pl#L557)

 Did you provide a CVS-delimiter at either the command-line or at [line 46.](https://github.com/Markismus/PocketBookDic/blob/master/pocketbookdic.pl#L46)

**Comment by Uwe-B** [comment]
Problem is the converter, it can't handle second or third tab.
My solution is at first replace (sample) \tnoun\t with (noun) and in the second walkthrough replacing all the remaining \t\t with space, since I want the grammatical entries like: noun, adj. etc. marked.

**Comment by Uwe-B** [comment]
CSV delimiter \t is at Line 46, it is the bad csv I get from dict.cc with several tabs in one entry.

**Comment by Uwe-B** [comment]
In retrospection I'm not sure how this can be handled by pocketbookdic.pl except via reading the header of the csv file:

> 

# EN-DE vocabulary database	compiled by dict.cc
# Date and time	2021-03-24 09:08
# License	THIS WORK IS PROTECTED BY INTERNATIONAL COPYRIGHT LAWS!
# License	Private use is allowed as long as the data, or parts of it, are not published or given away.
# License	By using this file, you agree to be bound to the Terms of Use published at the following URL:  
# License	https://www.dict.cc/translation_file_request.php
# Contains data from	http://dict.tu-chemnitz.de/ with friendly permission by Frank Richter, TU Chemnitz 
# Brought to you by	Paul Hemetsberger and the users of https://www.dict.cc/, 2002 - 2021

> 


and using it to recognize dict.cc files or leaving it to the user to postprepare it the *reconstructed.xdxf file like I did.

**Comment by Uwe-B** [comment]
After some research I'm sure it is not a pocketbookdic.pl failure but due to the excessive use of tabs in the source coming from dict.cc not only as delimiter and some flaws in converter.exe. I solved the problem by preparing the source csv file with:
`sed.exe -E -e "s/\t/@@@@/" -e "s/\t([^\t]+)\t/(\1)/g" -e "s/\t/ /g" -e "s/</(/g" -e "s/>/)/g" -e "s/@@@@/\t/" DictCC_En-DE.csv  > DictCC_En-DE_tab.csv`
Sorry to have bothered you again, closing the issue now.

**Comment by Markismus** [comment]
Just looked at a cvs-file from Dict.cc DE-EN and it is indeed very badly formatted. Probably due to the fact that they are inverting entries from EN-DE to DE-EN. It's not just that the delimiters are oddly placed, but also that the keywords aren't proper keywords, they also contain info and parts between paranthesis. 
E.g.
```
Bedienungsfehler {m}	faulty operation	noun	[tech.] 
Bedienungsfehler {m}	handling error	noun	
Bedienungsfehler {m}	operating error	noun	
```
So you can never use them as an exact keyword due to the info _m_. If you want to use this kind of info, it's better to identify multiple TAB symbols, check whether the first word is alphabetically ordered after the first word of the previous line and cut the line before the first  ` {`.

Dict.cc free, but it definitely needs to be reworked, before it is a proper dictionary.

I still am not convinced that `converter.exe` crashes on TAB symbols. Probably it's also due to badly formed key-words. However, you can check by replacing all TAB-symbols in the description of a key-word by `&#9;`. (The proper html-code for TAB.) This prevents all other interpretations of the TAB than html expression.

Just change[ line 865-867 ](https://github.com/Markismus/PocketBookDic/blob/master/pocketbookdic.pl#L867)from: 
```perl
$UnConverted =~ s~\&\#x([0-9A-Fa-f]{1,6});~chr("0x".$1)~seg ;
$UnConverted =~ s~\&\#([0-9]{1,6});~chr(int($1))~seg ;
```
to
```perl
$UnConverted =~ s~\&\#x([0-9A-Fa-f]{1,6});~chr("0x".$1)~seg ;
$UnConverted =~ s~\&\#([0-9]{1,6});~chr(int($1))~seg ;
# Add this line to change tabs back to html-code.
$UnConverted =~ s~\t~&#9;~sg ;
```
